name: Validate project

on:
  push:
env:
  PNPM_CACHE_FOLDER: .cache/pnpm
jobs:
  audit:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20.19.3]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-libs
        with:
          node-version: ${{ matrix.node-version }}
      - name: Audit packages
        run: pnpm audit --audit-level critical
    continue-on-error: true
  validate:
    needs: audit
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20.19.3]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-libs
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run linter
        run: pnpm lint
      - name: Run type-check
        run: pnpm type-check
